import {
  PartyPopper, Building2, UtensilsCrossed, Tag, Palette, Drama,
  Crown, Camera, Video, Heart, Sparkles, Music, Gift, Star,
  Cake, Wine, Flower2, Sparkle, Lightbulb, MicVocal, Disc3,
  Tent, Armchair, Sofa, Utensils, IceCreamCone, Candy,
  CalendarHeart, Users, Baby, GraduationCap, Church, Gem,
  Flame, Snowflake, Rainbow, Ribbon, ShieldCheck, Truck,
  type LucideIcon,
} from 'lucide-react';

/**
 * Debe mantenerse en espejo con apps/web/src/lib/serviceIcons.tsx —
 * la clave elegida aquí es la que renderiza el ícono SVG en la web pública.
 */
export const SERVICE_ICONS: Record<string, LucideIcon> = {
  party: PartyPopper,
  building: Building2,
  catering: UtensilsCrossed,
  tag: Tag,
  palette: Palette,
  drama: Drama,
  crown: Crown,
  camera: Camera,
  video: Video,
  heart: Heart,
  sparkles: Sparkles,
  music: Music,
  gift: Gift,
  star: Star,
  cake: Cake,
  wine: Wine,
  flower: Flower2,
  sparkle: Sparkle,
  lightbulb: Lightbulb,
  mic: MicVocal,
  dj: Disc3,
  tent: Tent,
  chair: Armchair,
  sofa: Sofa,
  utensils: Utensils,
  icecream: IceCreamCone,
  candy: Candy,
  calendar: CalendarHeart,
  guests: Users,
  baby: Baby,
  graduation: GraduationCap,
  church: Church,
  gem: Gem,
  flame: Flame,
  snowflake: Snowflake,
  rainbow: Rainbow,
  ribbon: Ribbon,
  shield: ShieldCheck,
  truck: Truck,
};

export const SERVICE_ICON_LABELS: Record<string, string> = {
  party: 'Fiesta',
  building: 'Empresarial',
  catering: 'Catering',
  tag: 'Promoción',
  palette: 'Decoración',
  drama: 'Show',
  crown: 'Quinceaños',
  camera: 'Fotografía',
  video: 'Filmación',
  heart: 'Bodas',
  sparkles: 'Mágico',
  music: 'Música',
  gift: 'Regalo',
  star: 'Destacado',
  cake: 'Pastel',
  wine: 'Brindis',
  flower: 'Flores',
  sparkle: 'Detalles',
  lightbulb: 'Iluminación',
  mic: 'Animación',
  dj: 'DJ / Sonido',
  tent: 'Toldos / Carpas',
  chair: 'Mobiliario',
  sofa: 'Lounge',
  utensils: 'Banquetes',
  icecream: 'Postres',
  candy: 'Dulces',
  calendar: 'Eventos',
  guests: 'Invitados',
  baby: 'Baby Shower',
  graduation: 'Graduación',
  church: 'Ceremonia',
  gem: 'Elegancia',
  flame: 'Velas',
  snowflake: 'Temporada',
  rainbow: 'Infantil',
  ribbon: 'Cotillón',
  shield: 'Seguridad',
  truck: 'Logística',
};

export const SERVICE_ICON_KEYS = Object.keys(SERVICE_ICONS);

export function isIconKey(value: string | undefined): value is keyof typeof SERVICE_ICONS {
  return !!value && value in SERVICE_ICONS;
}
